In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.max_columns', None)

In [35]:
df = pd.read_excel(r'C:\Users\NZK\OneDrive - University of Exeter\Desktop\Business Analytics\Business Project\data\smoke\data.xlsx')

In [7]:
df.sample(5)

ID Observation tower  Tower latitude  Tower longitude  Tower height  \
33    35.0         Hotchkiss       57.333933      -118.959333           990   
66    68.0               May       55.562298      -112.404908           866   
109  111.0           Petitot       59.523000      -119.606000           780   
0      1.0               Keg       57.640364      -118.352715           980   
44    46.0      Battle River       57.167680      -117.663980           674   

           Date  Year  Month  Day  Plume observation time   UTC  \
33   11-07-2012  2012      7   11                    1319  1919   
66   24-05-2013  2013      5   24                    1041  1641   
109  01-06-2014  2014      6    1                    1330  1930   
0    20-07-2010  2010      7   20                    1416  2016   
44   10-07-2012  2012      7   10                    1500  2100   

     Equilibrium plume top angle  Maximum plume top angle  Distance  \
33                           3.0                      9.0     23.45   
66                           2.0                      6.0     37.48   
109                         -1.0                      1.0     99.70   
0                           -0.5                   -999.0     28.60   
44                           3.0                   -999.0     89.86   

     Equilibrium plume top height  Maximum plume top height Fire name  \
33                    1266.315277               3753.422923    PWF068   
66                    1714.246291               4346.963959    LWF090   
109                   -808.929507               2672.319349    HWF058   
0                       37.530396               -999.000000    PWF104   
44                    5024.619022               -999.000000    PWF068   

      Latitude   Longitude  Fire elevation  Fire report time  \
33   57.151220 -119.153950             924               600   
66   55.898133 -112.456783             564               918   
109  59.972183 -118.065767             628              1243   
0    57.593183 -117.880700             764              1426   
44   57.151220 -119.153950             924              2052   

     Reported fire size Source  Maximum fire size Fuel     Temperature  \
33                  2.5      A            12732.0   C2         21.5714   
66                  2.0      A              123.8   S1         19.5614   
109                10.0      A              702.3   C2         19.8442   
0                   0.2      A                0.2   C2  Wind direction   
44                  2.5      A            12732.0   C2         25.6761   

     Relative humidity  Wind speed  Wind direction  24 hour precipitation  \
33             35.1255     16.1510             270                 0.0000   
66             33.7813     20.0897              90                 0.0000   
109            39.5539     13.2868             270                 0.4749   
0              51.4254      9.7450             135                 0.0933   
44             31.6990     17.3162             225                 0.0304   

        FFMC      DMC        DC      ISI      BUI      FWI      DSR  \
33   91.5856  44.9538  338.6180  12.6315  67.0135  29.7064  11.2966   
66   90.2255  39.5441  192.3422  13.9190  51.0362  26.9066  10.1098   
109  84.5882  32.7938  295.3170   7.1818  50.6877  17.0845   5.0616   
0    80.6583  11.3904  310.5377   2.5130  20.6834   4.2491   0.4999   
44   91.7783  41.4618  331.0340  13.9771  62.6567  30.7545  12.2345   

     Daily growth  Hourly growth         ROS         CFB           HFI  \
33     156.360993     116.790387   11.725492    0.836825  11850.661642   
66       8.045927       7.303828    4.082217    0.000000   7640.899468   
109   -999.000000    -999.000000 -999.000000 -999.000000   -999.000000   
0        0.168448       0.197128    0.447771    0.000000    143.299052   
44       2.245541       2.245541   16.015935    0.937433  16006.095184   

            SFC         TFC               Q           Notes  
33     2.699456    3.368917  91243000

In [ ]:
'Equilibrium plume top angle','Equilibrium plume top height','Maximum plume top height',
'Fire elevation','Temperature','Relative humidity','Wind speed','Wind direction','24 hour precipitation',
'FFMC','DMC','DC','ISI','BUI','FWI','DSR'

In [36]:
df['SIZE_ACRES']=df['Reported fire size'] / 2.471

In [121]:
df['SIZE_ACRES']=df['Reported fire size'] / 2.471
df.loc[df["SIZE_ACRES"] <= 1/4,"FIRE_SIZE"] = "Class A"
df.loc[(df["SIZE_ACRES"] <=10) & (df["SIZE_ACRES"] > 1/4),"FIRE_SIZE"] = "Class B"
df.loc[(df["SIZE_ACRES"] <=100) & (df["SIZE_ACRES"] > 10),"FIRE_SIZE"] = "Class C"
df.loc[(df["SIZE_ACRES"] <=300) & (df["SIZE_ACRES"] > 100),"FIRE_SIZE"] = "Class D"
df.loc[(df["SIZE_ACRES"] <=1000) & (df["SIZE_ACRES"] > 300),"FIRE_SIZE"] = "Class E"
df.loc[(df["SIZE_ACRES"] <=5000) & (df["SIZE_ACRES"] > 1000),"FIRE_SIZE"] = "Class F"
df.loc[df["SIZE_ACRES"] > 5000,"FIRE_SIZE"] = "Class G"
df["FIRE_SIZE"].value_counts()

Class B    100
Class C     44
Class A     25
Class E     17
Class D     16
Class F     15
Class G      3
Name: FIRE_SIZE, dtype: int64

In [128]:
df['SIZE_ACRES']=df['Reported fire size'] / 2.471
df.loc[df["SIZE_ACRES"] <= 1/4,"FIRE_SIZE"] = "Class A"
df.loc[(df["SIZE_ACRES"] <=10) & (df["SIZE_ACRES"] > 1/4),"FIRE_SIZE"] = "Class B"
df.loc[(df["SIZE_ACRES"] <=100) & (df["SIZE_ACRES"] > 10),"FIRE_SIZE"] = "Class C"
df.loc[(df["SIZE_ACRES"] > 100),"FIRE_SIZE"] = "Class D"
df["FIRE_SIZE"].value_counts()

Class B    100
Class D     51
Class C     44
Class A     25
Name: FIRE_SIZE, dtype: int64

In [81]:
df['SIZE_ACRES']=df['Reported fire size'] / 2.471
df.loc[df["SIZE_ACRES"] <= 1/4,"FIRE_SIZE"] = 1
df.loc[(df["SIZE_ACRES"] <=10) & (df["SIZE_ACRES"] > 1/4),"FIRE_SIZE"] = 2
df.loc[(df["SIZE_ACRES"] > 10),"FIRE_SIZE"] = 3
df["FIRE_SIZE"].value_counts()

2    100
3     95
1     25
Name: FIRE_SIZE, dtype: int64

In [38]:
x = df['Fire elevation']
y = df['FIRE_SIZE']
r = x.corr(y,method="kendall") 
r

0.1856331820180797

In [39]:
x = df['Maximum plume top height']
y = df['FIRE_SIZE']
r = x.corr(y,method="kendall") 
r

0.21319685028176383

In [40]:
x = df['Temperature']
y = df['FIRE_SIZE']
r = x.corr(y,method="kendall") 
r

0.26637170554624584

In [41]:
x = df['Relative humidity']
y = df['FIRE_SIZE']
r = x.corr(y,method="kendall") 
r

-0.036119115185880464

In [42]:
x = df['Wind speed']
y = df['FIRE_SIZE']
r = x.corr(y,method="kendall") 
r

0.07835736083053828

In [43]:
x = df['Wind direction']
y = df['FIRE_SIZE']
r = x.corr(y,method="kendall") 
r

0.1890642637312401

In [44]:
x = df['24 hour precipitation']
y = df['FIRE_SIZE']
r = x.corr(y,method="kendall") 
r

0.11656650943694889

In [45]:
x = df['FFMC']
y = df['FIRE_SIZE']
r = x.corr(y,method="kendall") 
r

0.06752704143447218

In [65]:
x = df['DMC']
y = df['FIRE_SIZE']
r = x.corr(y,method="kendall") 
r

0.2612814554300948

In [47]:
x = df['DC']
y = df['FIRE_SIZE']
r = x.corr(y,method="kendall") 
r

0.20333924666114114

In [48]:
x = df['ISI']
y = df['FIRE_SIZE']
r = x.corr(y,method="kendall") 
r

0.03254510978517865

In [49]:
x = df['BUI']
y = df['FIRE_SIZE']
r = x.corr(y,method="kendall") 
r

0.2856496740712436

In [50]:
x = df['FWI']
y = df['FIRE_SIZE']
r = x.corr(y,method="kendall") 
r

0.10716601042407412

In [51]:
x = df['DSR']
y = df['FIRE_SIZE']
r = x.corr(y,method="kendall") 
r

0.1208122128631174

In [52]:
x = df['Daily growth']
y = df['FIRE_SIZE']
r = x.corr(y,method="kendall") 
r

0.5063270823634413

In [53]:
x = df['Hourly growth']
y = df['FIRE_SIZE']
r = x.corr(y,method="kendall") 
r

0.4288931217653481

# Tree-based feature selection

In [54]:
from sklearn.feature_selection import SelectFromModel
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [179]:
a = df[['Fire elevation','Temperature','Relative humidity','Wind speed','Wind direction','24 hour precipitation',
        'FFMC','DMC','DC','ISI','BUI','FWI','DSR']]
b = df['FIRE_SIZE']
a = a.values.tolist()
b = b.values.tolist()

In [180]:
rf= RandomForestClassifier(n_estimators=500, n_jobs=1)

FS = SelectFromModel(rf).fit(a, b)
FS.get_support()

array([ True,  True, False,  True, False, False, False,  True,  True,
       False,  True, False, False])

In [181]:
FS.estimator_.feature_importances_

array([0.11626057, 0.11463072, 0.04856732, 0.08796051, 0.04328193,
       0.06580858, 0.05259982, 0.08998498, 0.08166991, 0.07016152,
       0.10399129, 0.05315391, 0.07192895])

In [ ]:
'Fire elevation','Temperature','Wind speed','DMC','DC','BUI'

# feature extraction

In [131]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction import DictVectorizer
from sklearn.preprocessing import StandardScaler

In [272]:
x = df[['Fire elevation','Temperature','Wind speed','DMC','DC','BUI']]
y = df['FIRE_SIZE']

x_train, x_test, y_train, y_test = train_test_split(x, y,random_state=6)

transfer = StandardScaler()
x_train = transfer.fit_transform(x_train)
x_test = transfer.transform(x_test)

# decision tree

In [115]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import roc_curve, auc, roc_auc_score

In [273]:

estimator = DecisionTreeClassifier() 

param_dict = {'max_depth': [3, 5, 8, 10, 15, 25, 30]}
estimator = GridSearchCV(estimator, param_grid=param_dict, cv=3)
estimator.fit(x_train, y_train)


y_predict = estimator.predict(x_test)
print('y_predict: \n', y_predict)
print('直接比对真实值和预测值: \n', y_test == y_predict)

score = estimator.score(x_test, y_test)
print('准确率为: \n', score)
print('最佳参数: \n', estimator.best_params_)
print('最佳结果: \n', estimator.best_score_)    
print('最佳估计器: \n', estimator.best_estimator_)    
print('交叉验证结果: \n', estimator.cv_results_)  

y_predict: 
 ['Class C' 'Class D' 'Class B' 'Class C' 'Class D' 'Class B' 'Class B'
 'Class A' 'Class D' 'Class D' 'Class B' 'Class B' 'Class D' 'Class B'
 'Class B' 'Class D' 'Class C' 'Class A' 'Class A' 'Class C' 'Class C'
 'Class B' 'Class D' 'Class D' 'Class B' 'Class D' 'Class B' 'Class D'
 'Class B' 'Class A' 'Class B' 'Class D' 'Class C' 'Class B' 'Class D'
 'Class D' 'Class C' 'Class D' 'Class B' 'Class C' 'Class B' 'Class B'
 'Class C' 'Class D' 'Class D' 'Class B' 'Class C' 'Class D' 'Class A'
 'Class B' 'Class C' 'Class C' 'Class B' 'Class B' 'Class A']
直接比对真实值和预测值: 
 90      True
52     False
49      True
134     True
13      True
188     True
19     False
174    False
136    False
197     True
182     True
187     True
54     False
99      True
6       True
11      True
176     True
87      True
21      True
148     True
160     True
59      True
146    False
165    False
64      True
162     True
120     True
12      True
30      True
56     False
65      True
4       Tr

In [274]:
from sklearn.metrics import classification_report
report = classification_report(y_test, y_predict)
print(report)

              precision    recall  f1-score   support

     Class A       0.67      0.67      0.67         6
     Class B       0.90      0.75      0.82        24
     Class C       1.00      0.80      0.89        15
     Class D       0.53      0.90      0.67        10

    accuracy                           0.78        55
   macro avg       0.77      0.78      0.76        55
weighted avg       0.83      0.78      0.79        55



In [116]:
y_true = np.where(y_test!='Class A',0,1) 
y_predict_ = np.where(y_predict!='Class A',0,1)
roc_auc_score(y_true, y_predict_)

0.7295918367346939

# random forest

In [118]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

In [275]:
estimator = RandomForestClassifier()

param_dict = {'n_estimators': [120, 200, 300, 500, 800, 1200],'max_depth': [5, 8, 15, 25, 30]}
estimator = GridSearchCV(estimator, param_grid=param_dict, cv=3)
estimator.fit(x_train, y_train)


y_predict = estimator.predict(x_test)
print('y_predict: \n', y_predict)
print('直接比对真实值和预测值: \n', y_test == y_predict)

score = estimator.score(x_test, y_test)
print('准确率为: \n', score)
print('最佳参数: \n', estimator.best_params_)

print('最佳结果: \n', estimator.best_score_)    
print('最佳估计器: \n', estimator.best_estimator_)    
print('交叉验证结果: \n', estimator.cv_results_)  

y_predict: 
 ['Class C' 'Class D' 'Class B' 'Class C' 'Class D' 'Class B' 'Class D'
 'Class B' 'Class D' 'Class D' 'Class B' 'Class B' 'Class D' 'Class B'
 'Class B' 'Class D' 'Class C' 'Class A' 'Class B' 'Class C' 'Class C'
 'Class B' 'Class D' 'Class D' 'Class B' 'Class D' 'Class B' 'Class D'
 'Class B' 'Class B' 'Class B' 'Class D' 'Class C' 'Class A' 'Class B'
 'Class D' 'Class C' 'Class D' 'Class B' 'Class C' 'Class B' 'Class B'
 'Class C' 'Class D' 'Class D' 'Class B' 'Class C' 'Class D' 'Class A'
 'Class B' 'Class C' 'Class C' 'Class B' 'Class B' 'Class B']
直接比对真实值和预测值: 
 90      True
52     False
49      True
134     True
13      True
188     True
19      True
174     True
136    False
197     True
182     True
187     True
54     False
99      True
6       True
11      True
176     True
87      True
21     False
148     True
160     True
59      True
146    False
165    False
64      True
162     True
120     True
12      True
30      True
56      True
65      True
4       Tr

In [276]:
from sklearn.metrics import classification_report
report = classification_report(y_test, y_predict)
print(report)

              precision    recall  f1-score   support

     Class A       1.00      0.50      0.67         6
     Class B       0.91      0.88      0.89        24
     Class C       1.00      0.80      0.89        15
     Class D       0.59      1.00      0.74        10

    accuracy                           0.84        55
   macro avg       0.88      0.79      0.80        55
weighted avg       0.89      0.84      0.84        55



# Logistic Regression feature select

In [277]:
a = df[['Fire elevation','Temperature','Relative humidity','Wind speed','Wind direction','24 hour precipitation',
        'FFMC','DMC','DC','ISI','BUI','FWI','DSR']]
b = df['FIRE_SIZE']
a = a.values.tolist()
b = b.values.tolist()
selector = SelectFromModel(LogisticRegression(penalty="l2", C=0.1)).fit(a, b)
selector.get_support()


C:\Users\NZK\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([False,  True,  True, False, False, False,  True,  True, False,
       False,  True, False, False])

In [278]:
array = selector.estimator_.coef_
array = pd.DataFrame(array)
array

0         1         2         3         4         5         6   \
0 -0.000646 -0.015776  0.015978 -0.001734 -0.004888 -0.003266  0.044338   
1 -0.002288 -0.016031  0.037468  0.003683  0.001193 -0.005518  0.026169   
2  0.001732  0.020992 -0.030137  0.008165  0.001963  0.008574 -0.043206   
3  0.001202  0.010815 -0.023310 -0.010114  0.001731  0.000210 -0.027301   

         7         8         9         10        11        12  
0 -0.028521 -0.000786 -0.001386 -0.031945 -0.001886 -0.002544  
1  0.006881 -0.006203  0.009286  0.003155  0.002840  0.007603  
2  0.025072  0.002909 -0.005629  0.006596  0.009433  0.007845  
3 -0.003433  0.004080 -0.002271  0.022193 -0.010387 -0.012904

In [283]:
array.to_excel(r'C:\Users\NZK\OneDrive - University of Exeter\Desktop\Business Analytics\Business Project\resultdata.xlsx')

# feature extraction

In [333]:
x = df[['Temperature','Relative humidity','FFMC','DMC','BUI']]
y = df['FIRE_SIZE']


x_train, x_test, y_train, y_test = train_test_split(x, y,random_state=6)

transfer = StandardScaler()
x_train = transfer.fit_transform(x_train)
x_test = transfer.transform(x_test)

# Logistic Regression

In [267]:
from sklearn.linear_model import LogisticRegression

In [318]:
print('回归系数: \n',estimator.coef_)
print('偏置: \n', estimator.intercept_)

回归系数: 
 [[-0.577254    0.14322048  0.83964229 -0.98325459 -0.14682242]
 [-0.23819705  0.05694743  0.01989144  0.24048611 -0.36178344]
 [ 0.57778487 -0.07562664 -0.50744741  1.22401611 -0.47404346]
 [ 0.23766618 -0.12454127 -0.35208633 -0.48124763  0.98264932]]
偏置: 
 [-0.34180576  0.24803151 -0.03618435  0.1299586 ]


In [334]:
estimator = LogisticRegression(multi_class='multinomial',solver='lbfgs',max_iter=1000)
estimator.fit(x_train, y_train)

y_predict = estimator.predict(x_test)
print('y_predict: \n', y_predict)
print('直接比对真实值和预测值: \n', y_test == y_predict)
score = estimator.score(x_test, y_test)
print('准确率为: \n', score)

y_predict: 
 ['Class B' 'Class B' 'Class B' 'Class D' 'Class B' 'Class B' 'Class B'
 'Class B' 'Class B' 'Class B' 'Class C' 'Class B' 'Class D' 'Class B'
 'Class B' 'Class B' 'Class B' 'Class B' 'Class B' 'Class D' 'Class D'
 'Class B' 'Class D' 'Class D' 'Class B' 'Class C' 'Class B' 'Class B'
 'Class B' 'Class B' 'Class B' 'Class B' 'Class D' 'Class A' 'Class B'
 'Class B' 'Class B' 'Class B' 'Class B' 'Class B' 'Class B' 'Class B'
 'Class D' 'Class D' 'Class D' 'Class B' 'Class D' 'Class D' 'Class B'
 'Class B' 'Class D' 'Class D' 'Class B' 'Class B' 'Class B']
直接比对真实值和预测值: 
 90     False
52      True
49      True
134    False
13     False
188     True
19     False
174     True
136    False
197    False
182    False
187     True
54     False
99      True
6       True
11     False
176    False
87     False
21     False
148    False
160    False
59      True
146    False
165    False
64      True
162    False
120     True
12     False
30      True
56      True
65      True
4      Fal

In [335]:
from sklearn.metrics import classification_report
report = classification_report(y_test, y_predict)
print(report)

              precision    recall  f1-score   support

     Class A       1.00      0.17      0.29         6
     Class B       0.61      0.96      0.74        24
     Class C       0.00      0.00      0.00        15
     Class D       0.21      0.30      0.25        10

    accuracy                           0.49        55
   macro avg       0.45      0.36      0.32        55
weighted avg       0.41      0.49      0.40        55



# KNN

In [139]:
from sklearn.neighbors import KNeighborsClassifier

In [157]:
estimator = KNeighborsClassifier() 


param_dict = {'n_neighbors': [1,3,5,7,9,11]}
estimator = GridSearchCV(estimator, param_grid=param_dict, cv=3)

estimator.fit(x_train, y_train)


y_predict = estimator.predict(x_test)
print('y_predict: \n', y_predict)
print('直接比对真实值和预测值: \n', y_test == y_predict)
score = estimator.score(x_test, y_test)
print('准确率为: \n', score)
print('最佳参数: \n', estimator.best_params_)
print('最佳结果: \n', estimator.best_score_)    
print('最佳估计器: \n', estimator.best_estimator_)    
print('交叉验证结果: \n', estimator.cv_results_)    

y_predict: 
 ['Class C' 'Class C' 'Class B' 'Class C' 'Class D' 'Class B' 'Class D'
 'Class B' 'Class D' 'Class D' 'Class B' 'Class B' 'Class D' 'Class B'
 'Class D' 'Class D' 'Class C' 'Class A' 'Class B' 'Class C' 'Class C'
 'Class B' 'Class C' 'Class C' 'Class D' 'Class D' 'Class B' 'Class D'
 'Class B' 'Class B' 'Class B' 'Class D' 'Class C' 'Class B' 'Class B'
 'Class C' 'Class C' 'Class B' 'Class B' 'Class C' 'Class B' 'Class B'
 'Class C' 'Class D' 'Class D' 'Class B' 'Class C' 'Class D' 'Class A'
 'Class B' 'Class C' 'Class C' 'Class A' 'Class B' 'Class D']
直接比对真实值和预测值: 
 90      True
52     False
49      True
134     True
13      True
188     True
19      True
174     True
136    False
197     True
182     True
187     True
54     False
99      True
6      False
11      True
176     True
87      True
21     False
148     True
160     True
59      True
146     True
165     True
64     False
162     True
120     True
12      True
30      True
56      True
65      True
4       Tr

In [158]:
from sklearn.metrics import classification_report
report = classification_report(y_test, y_predict)
print(report)

              precision    recall  f1-score   support

     Class A       0.67      0.33      0.44         6
     Class B       0.90      0.79      0.84        24
     Class C       0.88      0.93      0.90        15
     Class D       0.67      1.00      0.80        10

    accuracy                           0.82        55
   macro avg       0.78      0.76      0.75        55
weighted avg       0.83      0.82      0.81        55



# SVM feature select

In [222]:
from sklearn.svm import LinearSVC

In [298]:

a = df[['Fire elevation','Temperature','Relative humidity','Wind speed','Wind direction','24 hour precipitation',
        'FFMC','DMC','DC','ISI','BUI','FWI','DSR']]
b = df['FIRE_SIZE']
a = a.values.tolist()
b = b.values.tolist()
lsvc = SelectFromModel(LinearSVC(C=0.01, penalty="l1", dual=False)).fit(a, b)
lsvc.estimator_.coef_

C:\Users\NZK\anaconda3\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


array([[ 8.45355374e-05, -1.32434517e-02,  0.00000000e+00,
         0.00000000e+00, -9.76275492e-04,  0.00000000e+00,
         0.00000000e+00, -3.91379994e-03,  4.51483611e-04,
         0.00000000e+00, -4.98204568e-03,  0.00000000e+00,
         0.00000000e+00],
       [-1.18107190e-03, -6.87762555e-03,  1.68057842e-02,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.19159963e-02,  0.00000000e+00, -2.61541026e-03,
         7.26198003e-03, -1.55112012e-03,  0.00000000e+00,
         0.00000000e+00],
       [ 5.96763810e-04,  2.54829499e-02, -9.60877192e-03,
         4.97259170e-03,  2.91247376e-04,  0.00000000e+00,
        -2.37111021e-02,  9.76990145e-03,  6.69955625e-04,
         0.00000000e+00,  0.00000000e+00,  4.78445026e-03,
         0.00000000e+00],
       [ 4.88037240e-04,  1.80489719e-03, -1.03318168e-02,
         0.00000000e+00,  2.36265905e-04,  0.00000000e+00,
        -1.37322495e-02, -4.15109109e-04,  1.67205797e-03,
         0.00000000e+00,  3.83173412e

In [284]:
array = lsvc.estimator_.coef_
array = pd.DataFrame(array)
array

0         1         2         3         4    5         6         7   \
0  0.000084 -0.013205  0.000000  0.000000 -0.000976  0.0  0.000000 -0.004530   
1 -0.001181 -0.006867  0.016810  0.000000  0.000000  0.0  0.011910  0.000000   
2  0.000597  0.025394 -0.009633  0.004877  0.000291  0.0 -0.023661  0.009760   
3  0.000488  0.001809 -0.010330  0.000000  0.000237  0.0 -0.013733 -0.000517   

         8         9         10        11       12  
0  0.000426  0.000000 -0.004428  0.000000  0.00000  
1 -0.002616  0.007269 -0.001550  0.000000  0.00000  
2  0.000670  0.000000  0.000000  0.004797  0.00000  
3  0.001667  0.000000  0.003928  0.000000 -0.01177

In [285]:
array.to_excel(r'C:\Users\NZK\OneDrive - University of Exeter\Desktop\Business Analytics\Business Project\resultdata2.xlsx')

In [299]:
lsvc.get_support()

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True])

In [ ]:
'Fire elevation','Temperature','Relative humidity','Wind speed','Wind direction','FFMC','DMC','DC','ISI','BUI','FWI'

# feature extraction

In [313]:
x = df[['Temperature','Relative humidity','FFMC','DMC','DSR']]
y = df['FIRE_SIZE']

x_train, x_test, y_train, y_test = train_test_split(x, y,random_state=6)

transfer = StandardScaler()
x_train = transfer.fit_transform(x_train)
x_test = transfer.transform(x_test)

# SVM

In [143]:
from sklearn import svm

In [314]:
estimator = svm.SVC(C=1, gamma=1) 
estimator.fit(x_train, y_train) 

y_predict = estimator.predict(x_test)
print('y_predict: \n', y_predict)
print('直接比对真实值和预测值: \n', y_test == y_predict)
score = estimator.score(x_test, y_test)
print('准确率为: \n', score)

y_predict: 
 ['Class C' 'Class B' 'Class B' 'Class C' 'Class D' 'Class B' 'Class B'
 'Class B' 'Class D' 'Class D' 'Class B' 'Class B' 'Class B' 'Class B'
 'Class B' 'Class D' 'Class B' 'Class B' 'Class D' 'Class C' 'Class C'
 'Class B' 'Class C' 'Class B' 'Class B' 'Class B' 'Class B' 'Class D'
 'Class B' 'Class B' 'Class B' 'Class D' 'Class C' 'Class A' 'Class B'
 'Class B' 'Class C' 'Class D' 'Class B' 'Class C' 'Class B' 'Class B'
 'Class C' 'Class D' 'Class D' 'Class B' 'Class C' 'Class D' 'Class A'
 'Class B' 'Class C' 'Class C' 'Class B' 'Class B' 'Class D']
直接比对真实值和预测值: 
 90      True
52      True
49      True
134     True
13      True
188     True
19     False
174     True
136    False
197     True
182     True
187     True
54     False
99      True
6       True
11      True
176    False
87     False
21     False
148     True
160     True
59      True
146     True
165    False
64      True
162    False
120     True
12      True
30      True
56      True
65      True
4       Tr

In [310]:
from sklearn.metrics import classification_report
report = classification_report(y_test, y_predict)
print(report)

              precision    recall  f1-score   support

     Class A       1.00      0.33      0.50         6
     Class B       0.79      0.96      0.87        24
     Class C       1.00      0.80      0.89        15
     Class D       0.67      0.80      0.73        10

    accuracy                           0.82        55
   macro avg       0.86      0.72      0.75        55
weighted avg       0.85      0.82      0.81        55



# Bayes

In [161]:
from sklearn.naive_bayes import BernoulliNB
estimator = BernoulliNB() 
estimator.fit(x_train, y_train) 

y_predict = estimator.predict(x_test)
print('y_predict: \n', y_predict)
print('直接比对真实值和预测值: \n', y_test == y_predict)
score = estimator.score(x_test, y_test)
print('准确率为: \n', score)

y_predict: 
 ['Class B' 'Class C' 'Class C' 'Class C' 'Class B' 'Class B' 'Class B'
 'Class B' 'Class C' 'Class B' 'Class C' 'Class B' 'Class C' 'Class B'
 'Class C' 'Class B' 'Class C' 'Class B' 'Class B' 'Class C' 'Class C'
 'Class B' 'Class C' 'Class C' 'Class D' 'Class C' 'Class B' 'Class B'
 'Class B' 'Class B' 'Class B' 'Class B' 'Class C' 'Class B' 'Class B'
 'Class C' 'Class B' 'Class B' 'Class B' 'Class B' 'Class B' 'Class B'
 'Class C' 'Class B' 'Class B' 'Class B' 'Class C' 'Class B' 'Class C'
 'Class B' 'Class B' 'Class C' 'Class B' 'Class B' 'Class B']
直接比对真实值和预测值: 
 90     False
52     False
49     False
134     True
13     False
188     True
19     False
174     True
136     True
197    False
182    False
187     True
54     False
99      True
6      False
11     False
176     True
87     False
21     False
148     True
160     True
59      True
146     True
165     True
64     False
162    False
120     True
12     False
30      True
56      True
65      True
4      Fal

In [162]:
from sklearn.metrics import classification_report
report = classification_report(y_test, y_predict)
print(report)

              precision    recall  f1-score   support

     Class A       0.00      0.00      0.00         6
     Class B       0.51      0.75      0.61        24
     Class C       0.58      0.73      0.65        15
     Class D       0.00      0.00      0.00        10

    accuracy                           0.53        55
   macro avg       0.27      0.37      0.31        55
weighted avg       0.38      0.53      0.44        55



C:\Users\NZK\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# AdaBoost

In [150]:
from sklearn.ensemble import AdaBoostClassifier

In [163]:

estimator = AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
        learning_rate=1.0, n_estimators=100, random_state=0)
estimator.fit(x_train, y_train) 

y_predict = estimator.predict(x_test)
print('y_predict: \n', y_predict)
print('直接比对真实值和预测值: \n', y_test == y_predict)
score = estimator.score(x_test, y_test)
print('准确率为: \n', score)

y_predict: 
 ['Class C' 'Class C' 'Class B' 'Class C' 'Class D' 'Class B' 'Class B'
 'Class B' 'Class D' 'Class D' 'Class C' 'Class B' 'Class C' 'Class B'
 'Class D' 'Class D' 'Class D' 'Class B' 'Class B' 'Class C' 'Class C'
 'Class B' 'Class C' 'Class C' 'Class B' 'Class C' 'Class D' 'Class D'
 'Class B' 'Class A' 'Class B' 'Class D' 'Class C' 'Class A' 'Class A'
 'Class C' 'Class C' 'Class B' 'Class D' 'Class B' 'Class B' 'Class B'
 'Class C' 'Class B' 'Class B' 'Class A' 'Class C' 'Class D' 'Class A'
 'Class D' 'Class C' 'Class C' 'Class B' 'Class B' 'Class A']
直接比对真实值和预测值: 
 90      True
52     False
49      True
134     True
13      True
188     True
19     False
174     True
136    False
197     True
182    False
187     True
54     False
99      True
6      False
11      True
176    False
87     False
21     False
148     True
160     True
59      True
146     True
165     True
64      True
162    False
120    False
12      True
30      True
56     False
65      True
4       Tr

In [164]:
from sklearn.metrics import classification_report
report = classification_report(y_test, y_predict)
print(report)

              precision    recall  f1-score   support

     Class A       0.50      0.50      0.50         6
     Class B       0.70      0.58      0.64        24
     Class C       0.71      0.80      0.75        15
     Class D       0.50      0.60      0.55        10

    accuracy                           0.64        55
   macro avg       0.60      0.62      0.61        55
weighted avg       0.64      0.64      0.64        55

